---
title: "Úvodní hodina"
subtitle: "Zpracovávání výzkumných dat pomocí jazyka R"
title-slide-attributes:
  data-background-color: rgb(233, 84, 32)
format:
  revealjs:
    self-contained: true
    theme: default
    scrollable: true
    footer: "Charleston | [Lucie Hošková](https://orcid.org/0009-0001-9695-2342)"
engine: knitr
filters:
  - webr
execute:
  echo: true
  warning: false
  cache: true
---

## Programme

::: incremental
- short intoructionary and admin window aka Where Can You Find Coffee
- R basics 101 review
- so what type of data am I actually working with and why do I need to know?
- ukládání dat do proměnných
- operátory
- etiketa psaní kódu
- working directory
- RProjekty, .RData
- funkce v R a jejich syntax
:::

## Types of data
why it is important to know the difference

qualitaitve data diskrétní
- nominal data
- ordinal data

quantitative data spojitá
- interval data
  - pokracuje to jak je treba, -25 stupnu je porad hodnota, nema to neco jako jasnou nulu
  - nelze porovnavat - teplota v celsius nemuze byt napriklad dvakrat tak vetsi, protoze... dvakrat tak vetsi od ceho? 
    - 40C neni 2x vetsi nez 20C, protoze nula neni zacatek od ktereho se to pocita
- ratio
  - jasna nula; nelze mit zapornou vysku nebo treba prijem, taky nelze jit do minusu se stupni kelvina
  

is it possible to change those types? yes fo example dividing height into categories

## Loading the data
load the newborns.txt file. what function will we use? how will we do it?

what types are the different variables? what function to use
changing to factors - if its categories which use numbers for names it will take it as numeric and for example barlots will go haywire

changing to factors

## Example of base R

# why you should use ggplot2 instead

## Barplot
for categorical data
or rather - numeric values of the categories
categories on x the numeric values on y
it is possible to do how much is of each category like with histogram
aka count

https://lucie-hoskova.quarto.pub/r_pro_analyzu_vedeckych_dat/letni_skola.html#/barplot

## 3D graphs
library(rgl)

x <- rnorm(100)
y <- rnorm(100)
z <- rnorm(100)

plot3d(x, y, z, col = "blue", pch = 20, size = 2, xlab = "X", ylab = "Y", zlab = "Z")
#v prezentaci se nezobrazi, musi byt spusten v RStudiu
